image: gabiacloud/node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    
swagger:
  stage: build
  script:
    - npm run swagger-merge
    

nightwatch:
  stage: test
  script: 
    - npm run cpapi.gabia.com/docs



publish:  
  stage: deploy
  only:
    - master
  script:
    - npm build
    - mkdir .public
    - cp index.html .public/
    - cp api.yaml .public/
    - cp -r static .public/
    - mv .public public
  artifacts:
    paths:
    - public