swagger: 2.0
schemes:
  - http
host: 10.222.222.227:3000
basePath: /v1
info:
  $ref: ./swagger.dev/info/index.yaml
produces:
  - application/json
tags:
  $ref: ./swagger.dev/tags/index.yaml
parameters:
  $ref: ./swagger.dev/parameters/index.yaml
paths:
  $ref: ./swagger.dev/paths/index.yaml
definitions:
  $ref: ./swagger.dev/definitions/index.yaml