swagger: '2.0'
schemes:
  - https
host: cpapi.gabia.com
basePath: /v1
info:
  $ref: ./info/index.yaml
produces:
  - application/json
tags:
  $ref: ./tags/index.yaml
parameters:
  $ref: ./parameters/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml